# LikeC4 configuration
# Docs: https://likec4.dev/docs/reference/config

name: bookly

sources:
  - "./spec.c4"
  - "./model"
  - "./views"

output: "./out"

formats:
  - svg
  - png
  - json

editor:
  port: 3051
